export declare const ss: (selector: string) => () => void | undefined;
export declare const cn: (...classes: any[]) => string;
export declare const chunk: (arr: any[], size: number) => any;
export declare const isEmail: (str: string) => boolean;
export declare const composeSlug: (str: string) => string;
export declare const escapeHtml: (str: string) => string;
export declare const removeHtml: (str: string) => string;
export declare const composeExcerpt: (str: string, charLimit: number, useEllipsis?: boolean) => string;
export declare const composeFacebookShareLink: (url: string) => string;
export declare const composeTwitterShareLink: (url: string) => string;
export declare const purifySubmitFields: (submitEvent: any) => any[];
export declare const formToHtml: (heading: string | undefined, submitEvent: any) => string;
export declare const formToObject: (submitEvent: any) => null;
export declare function query(url: string, { method, headers, ...body }: any, json?: boolean): Promise<any>;
export declare const closeModal: (selector: any, data?: Object | undefined) => void;
export declare const openModal: (selector: any, data?: Object | undefined) => void;
export declare const toggleModal: (selector: any, data?: Object | undefined) => void;
export declare const closeExpand: (selector: any, data?: Object | undefined) => void;
export declare const openExpand: (selector: any, data?: Object | undefined) => void;
export declare const toggleExpand: (selector: any, data?: Object | undefined) => void;
export declare const onIntersect: (selector: string, callback: Function, offset?: string, once?: boolean) => void;
export declare const initLazyLoad: (offset?: string) => void;
export declare const initScrollView: (offset?: string) => void;
export declare const initSplitLetters: (selector: string, delay?: number, step?: number) => void;
